### ISSUE TITLE
Support for T5 model

### ISSUE THREAD

**Issue by wmmxk** [PAIR-code/lit#10]
In the paper introducing lit, T5 model is used in the section entitled "debugging text generation". But I did not find the support for T5 model in the ```pretrained_lm_demo.py``` file. It seems that only ["bert-" and "gpt2"](https://github.com/PAIR-code/lit/blob/80f4f771a93ebd6c294f29d827f3993bc830958b/lit_nlp/examples/pretrained_lm_demo.py#L64) are supported for now. Am I right?

**Comment by iftenney** [comment]
Coming soon! We're just cleaning up the code on this one.

**Comment by iftenney** [comment]
This is available now in https://github.com/PAIR-code/lit/blob/main/lit_nlp/examples/t5_summarization_demo.py
