### ISSUE TITLE
Running LIT inside of Google Colab

### ISSUE THREAD

**Issue by githubrandomuser2017** [PAIR-code/lit#14]
Is it possible to run the Language Interpretability Tool inside of Google Colab?

If not, are there plans to support this setup?

**Comment by jameswex** [comment]
Thanks for reaching out. We don't yet support using the tool inside Colab but we do plan on looking into it now that we've gotten the initial version out.

**Comment by jameswex** [comment]
LIT now works in colab and jupyter as of version 0.3. See instructions and a link to a demo in the readme and on the LIT website demo page.
