### ISSUE TITLE
Widget on Google Cloud Vertex AI Workbench Notebook

### ISSUE THREAD

**Issue by toki-debug** [PAIR-code/lit#1463]
Hi! I would like to use a widget for Google Cloud Vertex AI Notebook, but I'm a little confused about how to do it properly. I tried to search in the documentation, but I'm not entirely sure about how to do it.

![image](https://github.com/PAIR-code/lit/assets/62253403/b8e24f43-cb46-4ffe-ab3a-cbe9fb13443e)

**Comment by bdu91** [comment]
Hello, can you elaborate a bit about how you set up the notebook? I don't know the if `proxy_url` is causing the problem here.

Since you mentioned Google Cloud Vertex AI notebook, this is the path I tried: 
1. [Vertex AI notebook website](https://cloud.google.com/vertex-ai-notebooks), click "Go to Console"
1. this bring me to the Google Cloud Colab Enterprise page and I opened one of the "intro_gemini_pro_python.ipynb" notebooks (any notebook should work or create a new one)
1. I then connected to a default Vertex AI runtime, pip installed LIT there and tried [one of our examples](https://colab.sandbox.google.com/github/google/generative-ai-docs/blob/main/site/en/gemma/docs/lit_gemma.ipynb) (basically copied the code into the notebook opened at step 2 and used a GPT2 model instead of Gemma since the runtime at step 2 is CPU) and was able to load the widget.

**Comment by toki-debug** [comment]
Hello! :)
I'm currently using Vertex AI Workbench. I've gained access to a project machine and am utilizing JupyterLab notebooks there. I would like to know if it's possible to use widgets there. When running just with the port, it displays the same page as shown with the proxy.

![image](https://github.com/PAIR-code/lit/assets/62253403/d81bb7db-135c-472e-9b38-5138a980dc1b)

**Comment by bdu91** [comment]
Hello, I am relatively new to Vertex AI Workbench, but I also tried to render LIT widget and it seems to work fine, here is the process I went through:
* On the Workbench entry page, I started an instance at zone "us-central1-a", version "M115", machine type "Efficient Instance: 4 vCPUs, 16 GB RAM" and clicked "OPEN JUPYTERLAB".
* This brings me to a new page that opens up an ipynb notebook. I did the necessary pip install in the terminal, and copied the code from the [public demo](https://colab.sandbox.google.com/github/PAIR-code/lit/blob/main/lit_nlp/examples/notebooks/LIT_sentiment_classifier.ipynb) found on Github and it seems to work fine, with screenshot attached.
Let me know if there is anything different you've done that could cause the issue.
![VertexAI_workbench_LIT](https://github.com/PAIR-code/lit/assets/8292874/3f8ac7cb-5465-4853-9948-ac2d6da975c7)

**Comment by toki-debug** [comment]
I see, so it might be a problem with my version. I'm currently working with lit-nlp Version 0.5.0, as I need to use Python 3.9 to run my models :/

**Comment by RyanMullins** [comment]
I might be able to relax the Python version requirements to include 3.9... I'll investigate and get back to you later this week or early next. 

Out of curiosity, which modeling framework are you using that requires Py3.9?

**Comment by toki-debug** [comment]
Oh, thanks, that would be very helpful! :)
The model pipeline doesn't actually require Python 3.9, but there are some important dependencies from where I get the model trained that needs this version.

**Comment by toki-debug** [comment]
Hey, @RyanMullins! Just checking in, any updates on it?

**Comment by RyanMullins** [comment]
Sorry, had to deal with some other tasks this week. Planning to look at this tomorrow (Fri 24 May 2024) and give you and update. We don't use many Py3.10+ features, though I know we use `strict=True` on a few `zip()` calls that will need to be reverted. Hopefully it's not much more complicated than that.

**Comment by toki-debug** [comment]
I completely understand that other tasks can take priority and I sincerely appreciate your efforts on this matter! Looking forward to your update tomorrow. Thanks for your efforts on this! :)

**Comment by RyanMullins** [comment]
@toki-debug the PR above addresses the Python 3.9 compatibility issues (thankfully they were all minor). We aren't planning a formal release for about another month, so you'll need to install the `dev` branch via git in the meantime.

```shell 
pip install git+https://github.com/PAIR-code/lit.git@dev
```

**Comment by toki-debug** [comment]
Thank you so much, @RyanMullins! I will test it as soon as possible and let you know if everything is working as it should. Thanks again for being so attentive and fast; I really appreciate your efforts! 😄

**Comment by toki-debug** [comment]
Everything seems to be working completely fine, thanks again!!

**Comment by toki-debug** [comment]
Everything seems to be working completely fine, thanks again!!
