### ISSUE TITLE
Relax shap version

### ISSUE THREAD

**Issue by hentt30** [PAIR-code/lit#1471]
Is it possible to relax the shap version requirement to >=0.42.0? I am using LIT together with powershap 0.0.11 and I'm experiencing dependency conflicts.

## Steps to Reproduce

Run the following command:
```
pip install git+https://github.com/PAIR-code/lit.git@dev powershap==0.0.11
```

## Error Message

```
ERROR: Cannot install lit-nlp==1.1.1 and powershap==0.0.11 because these package versions have conflicting dependencies.

The conflict is caused by:
    powershap 0.0.11 depends on shap<0.46.0 and >=0.45.0
    lit-nlp 1.1.1 depends on shap==0.42.0
```

**Comment by RyanMullins** [comment]
Looks like the tests pass in https://github.com/PAIR-code/lit/pull/1472 so yes I think we can relax this. Will leave this issue open until you verify the fix works for you.

**Comment by RyanMullins** [comment]
FYI #1472 was merged. Let me know if there's anything else I can do to make this work for you.

**Comment by hentt30** [comment]
Tks, I'll try it out in a while and will let you know how it went.

**Comment by hentt30** [comment]
It worked, Thank you!
