### ISSUE TITLE
bert-base-uncased.cache.pkl does not exist, not loading

### ISSUE THREAD

**Issue by adeepH** [PAIR-code/lit#16]
![literror](https://user-images.githubusercontent.com/46108405/90960082-c34fe880-e4bc-11ea-9492-0e9f3dc6a8df.PNG)

Thus I get the message `not found`  at `http://127.0.0.1:5432`

**Comment by jameswex** [comment]
So are you able to run LIT with the additions you made to the install steps? If so, what exactly was necessary?

**Comment by adeepH** [comment]
Yes, I am able to run LIT . After running `conda install m2-base` on anaconda powershell prompt , I could run yarn && yarn build steps. Thank you
