### ISSUE TITLE
Error encountered during fresh install

### ISSUE THREAD

**Issue by minggnim** [PAIR-code/lit#180]
After fresh installed the package and ran both demos, the following error occurred

>tensorflow_datasets.core.download.downloader.DownloadError: Failed to get url https://firebasestorage.googleapis.com/v0/b/mtl-sentence-representations.appspot.com/o/data%2FSST-2.zip?alt=media&token=aabc5f6b-e466-44a2-b9b4-cf6337f84ac8. HTTP code: 403.

any ideas?

**Comment by jameswex** [comment]
Yes it seems that the tensorflow-datasets package moved some data files we depend on but has not yet released a new version of their pip package. Please try uninstalling tensorflow-datasets package, and installing the tfds-nightly package (of their nightly build). This should be resolved when they release a new official pip version.

**Comment by minggnim** [comment]
> Yes it seems that the tensorflow-datasets package moved some data files we depend on but has not yet released a new version of their pip package. Please try uninstalling tensorflow-datasets package, and installing the tfds-nightly package (of their nightly build). This should be resolved when they release a new official pip version.

Yeah, using `tfds-nightly` resolves it. Thanks!
