### ISSUE TITLE
documentation to write a new component 

### ISSUE THREAD

**Issue by cuent** [PAIR-code/lit#183]
Can you point me out how to write a new component? I would like to write a new component and extend the projector with knn. So when you click a datapoint it would highlight the closest points.

**Comment by iftenney** [comment]
Documentation for the frontend client is here: https://github.com/PAIR-code/lit/blob/main/documentation/client.md , and there's a bit more on adding custom frontend components here: https://github.com/PAIR-code/lit/blob/main/documentation/development.md#custom-client--modules

For something like nearest neighbors, you may want to fork the embedding module and go from there. If you need an additional backend component, you can implement the `Interpreter` interface: https://github.com/PAIR-code/lit/blob/main/lit_nlp/api/components.py#L27 and pass your component to the server constructor - then it should be available by name to API calls to `/get_interpretations`.

Hope this helps! We've had a few requests for a feature like this but haven't had a chance to work on it yet, so if you do get this working please send us a PR :)

**Comment by iftenney** [comment]
Closing this - embedding projector should now have this feature by default:
![UWv6F5qceRj3Rmd](https://user-images.githubusercontent.com/2609401/142138920-a90929e4-6b55-4846-b810-1a4ea9a47df8.png)
