### ISSUE TITLE
Can't get any metrics, predictions or explanations

### ISSUE THREAD

**Issue by lben** [PAIR-code/lit#184]
Hi, I have followed the developer guide and tried to do some baby steps with a simple classifier but I cannot make it work. I just can see my data within the DataTable and select data points but I can't see anything within the Predictions or Expalnations tab; besides there is no error message in the status bar so I am not sure what I am doing wrong.

My data wrapper has the following spec:
```
def spec(self):
    return {
        message': lit_types.TextSegment(),
        label': lit_types CategoryLabeL(vocab=self.vocab)
    }
```

and my self._examples is a list in the following format:
`
[{'message': 'text1', 'label': 'OPTION_1'}, {'message': 'text2', 'label': 'OPTION_1'}, {'message': 'text3', 'label': 'OPTION_2'} ...... and so on]
`

In My model wrapper I have the following functions defined:

```
def max_minibatch_size(self, config=None):
    return 32

def predict_minibatch(self, inputs, config=None):
    result = self._model.predict([v['message'] for v in inputs])
    predictions = [{'label': label} for label in self.classificationEncoder.inverse_transform(results.argmax(-1))]
    return predictions   # [{'label': 'OPTION_1'}, {'label': 'OPTION_2'}, ... and so on]

def input_spec(self):
    return {
        'message': lit_types.TextSegment()
    }

def output_spec(self):
    return {
        'label': lit_types.CategoryLabel(vocab=list(self.classes))
    }
```

Finally, my main file is as follows:

```
from absl import app
from absl import logging

from lit_nlp import dev_server
from lit_nlp import server_flags

from ClassifierDataWrapper import ClassifierDataWrapper
from ClassifierModelWrapper import ClassifierModelWrapper


def main(_):
    datasets = {
        'classifier_dataset': ClassifierDataWrapper()
    }

    models = {
        'classifier_model': ClassifierModelWrapper()
    }

    flags = server_flags.get_flags()
    # flags['host'] = '0.0.0.0'
    lit_demo = dev_server.Server(models, datasets, **flags)
    lit_demo.serve()


if __name__ == '__main__':
    app.run(main)
```

This only shows me the DataTable but anything else inside the tabs, am I doing something wrong?

Thank you!

**Comment by iftenney** [comment]
For classifiers, most modules are designed to look for a `MulticlassPreds` field in the output, which contains the probabilities for each target class. So you'd have something like:

```
def output_spec(self):
  return {'predicted_label': lit_types.MulticlassPreds(vocab=list(self.classes), parent='label')
```

(also note the `parent=` field - this tells LIT which input field it should be compared to when computing metrics)

In this case, you'd return predictions that look like: `[{'label': [0.8, 0.1, 0.1]}, {'label': [0.03, 0.9, 0.07}, ... ]`

As a reference, you can see the return types from one of the classifier demos: https://github.com/PAIR-code/lit/blob/main/lit_nlp/examples/simple_tf2_demo.py#L106
