### ISSUE TITLE
HTTP code: 403 

### ISSUE THREAD

**Issue by jeesunkim** [PAIR-code/lit#200]
Win 10
installed LIT by pip install lit-nlp
ran conda env create -f environment.yml
activated the env
ran the first demo
python -m lit_nlp.examples.glue_demo --port=5432 --quickstart
this resulted in this error:
tensorflow_datasets.core.download.downloader.DownloadError: Failed to get url https://firebasestorage.googleapis.com/v0/b/mtl-sentence-representations.appspot.com/o/data%2FSST-2.zip?alt=media&token=aabc5f6b-e466-44a2-b9b4-cf6337f84ac8. HTTP code: 403.
i.e., a Permission denied error
Any help appreciated.

**Comment by iftenney** [comment]
This looks like an issue from tensorflow_datasets, can you try the fix mentioned in #180?

**Comment by jeesunkim** [comment]
Ok, fixed - I simply populated the build dir etc from the anaconda environment, i.e., anaconda3\envs\trans\Lib\site-packages\lit_nlp\client\build - now works a treat. Thanks again
