### ISSUE TITLE
Visualizing multiple datasets

### ISSUE THREAD

**Issue by ajhepburn** [PAIR-code/lit#201]
I am currently working with examining saliency and attention patterns between multiple interrelated classification tasks. Is there a way for me to view the same dataset with different target variables and different models?

I know that I'm able to compare two models side-by-side but the issue is that they have different target variable distributions (even though the targets are still 1, 0)

**Comment by iftenney** [comment]
You can compare models that have different output types; the only requirement is that they're both compatible with the same input data (i.e. the dataset matches all `required` fields in the model's `input_spec()`). So if you have something like:

```
# model A
def output_spec(self):
  return {'pred_foo': MulticlassPreds(vocab=['0', '1'], parent='foo')}
```

and

```
# model B
def output_spec(self):
  return {'pred_bar': MulticlassPreds(vocab=['0', '1'], parent='bar')}
```

they should both show up in the UI, and if you have both selected you'll see info for `pred_foo` from model A and for `pred_bar` from model B.
