### ISSUE TITLE
input and output specs for machine translation

### ISSUE THREAD

**Issue by rezasjourney** [PAIR-code/lit#21]
I am having some issues displaying outputs of machine translation models. Is there an example of `input_spec` and `output_spec` functions for a machine translation model class (or for sequence to sequence models in general)?

**Comment by iftenney** [comment]
For a basic seq2seq, something like this should work:

```python
def input_spec(self):
  return {"source": lit_types.TextSegment()}

def output_spec(self):
  return {"generated": lit_types.GeneratedText()}
```

The values for each would be a single string - see https://github.com/PAIR-code/lit/blob/main/docs/development.md#available-types.

**Comment by iftenney** [comment]
If you have references and want BLEU scores, you can do:

```python
def input_spec(self):
  return {
    "source": lit_types.TextSegment(), 
    "target": lit_types.TextSegment(required=False),
  }

def output_spec(self):
  return {"generated": lit_types.GeneratedText(parent="target")}
```

**Comment by rezasjourney** [comment]
Great, thanks! It's working fine now. I'm not necessarily interested in any metrics right now but setting `parent="target"` gives me a `KeyError: 'generated'` in metrics.py. I do have references/targets though!

**Comment by iftenney** [comment]
Great!

For the metrics error, can you post the full trace?

You do also need to make sure the target field is in the dataset spec, e.g.

```python
# in Dataset class def
def spec(self):
  return {
    "source": lit_types.TextSegment(), 
    "target": lit_types.TextSegment(),
  }
```

(Example here: https://github.com/PAIR-code/lit/blob/main/lit_nlp/examples/datasets/mt.py)

**Comment by rezasjourney** [comment]
Yes, I do have both source and target in the `spec` function. This is the full traceback:

``` python
Traceback (most recent call last):
  File "/Users/rfazeli/projects/lit/lit_nlp/lib/wsgi_app.py", line 193, in __call__
    return self._ServeCustomHandler(request, clean_path)(environ,
  File "/Users/rfazeli/projects/lit/lit_nlp/lib/wsgi_app.py", line 178, in _ServeCustomHandler
    return self._handlers[clean_path](self, request)
  File "/Users/rfazeli/projects/lit/lit_nlp/app.py", line 77, in _handler
    outputs = fn(data, **kw)
  File "/Users/rfazeli/projects/lit/lit_nlp/app.py", line 240, in _get_interpretations
    config=data.get('config'))
  File "/Users/rfazeli/projects/lit/lit_nlp/api/components.py", line 71, in run_with_metadata
    model_outputs, config)
  File "/Users/rfazeli/projects/lit/lit_nlp/components/metrics.py", line 123, in run_with_metadata
    preds = [mo[pred_key] for mo in model_outputs]
  File "/Users/rfazeli/projects/lit/lit_nlp/components/metrics.py", line 123, in <listcomp>
    preds = [mo[pred_key] for mo in model_outputs]
KeyError: 'generated'
```

**Comment by iftenney** [comment]
Hmm - it looks like it's missing in the model outputs then? What are the contents of `model_outputs[0]` ?

**Comment by rezasjourney** [comment]
I'm assuming `model_outputs` would contain the output of the `predict_minibatch()` function in the model class. In that case, the output is a list of dictionaries like this:
``` python
[
 {
 "generated": prediction
 }
for prediction in predictions]
```

**Comment by iftenney** [comment]
That looks correct, but possible that something else is wrong. You should be able to debug with `pdb` - if you add a breakpoint or `pdb.set_trace()` at that line (in metrics.py) it'll give you a debug line inside that request.

**Comment by rezasjourney** [comment]
It seems like my changes were not being applied because the app would just read the previous predictions from the cached data at `/tmp/lit_data/model.cache.pkl`. When I delete this file before running the app, the changes are applied and both predictions and targets are returned and compared in the UI.

**Comment by iftenney** [comment]
Great! Is everything working now?

**Comment by rezasjourney** [comment]
Yes, it's all good! Thanks for your help.
