### ISSUE TITLE
demos not working

### ISSUE THREAD

**Issue by flaviaas23** [PAIR-code/lit#217]
Hello,
I have installed LIT and I am trying to run the demos, but everytime I try it doesn't work.
I run: 
python -m lit_nlp.examples.pretrained_lm_demo --models=bert-base-uncased --port=5432
and 
python -m lit_nlp.examples.glue_demo --port=5432 --quickstart
error message at the end:
"tensorflow_datasets.core.download.downloader.DownloadError: Failed to get url https://firebasestorage.googleapis.com/v0/b/mtl-sentence-representations.appspot.com/o/data%2FSST-2.zip?alt=media&token=aabc5f6b-e466-44a2-b9b4-cf6337f84ac8. HTTP code: 403"

Could you help on that?
BR
Flavia

**Comment by jameswex** [comment]
Please try uninstalling tensorflow-datasets pip package, and instead install tfds-nightly pip package

**Comment by santhoshrajamanickam** [comment]
> Please try uninstalling tensorflow-datasets pip package, and instead install tfds-nightly pip package

Had the same issue, but this solution solved it!

**Comment by flaviaas23** [comment]
Thank you James!
you solution worked for me.
