### ISSUE TITLE
Server aborted the SSL handshake when reading metadata of gs://tfds-data/datasets/glue

### ISSUE THREAD

**Issue by JackyDai1996** [PAIR-code/lit#22]
Hi,

While running python -m lit_nlp.examples.quickstart_sst_demo --port=5432, the error shows up. I am wondering if there is a solution to this? Thanks you!

I0827 11:42:16.742576 4549361088 quickstart_sst_demo.py:47] Working directory: /var/folders/8s/t30hz5ys1v9_r8drjl_5v1mc0000gn/T/tmpyqqb40ez
2020-08-27 11:42:16.747240: W tensorflow/core/platform/cloud/google_auth_provider.cc:184] All attempts to get a Google authentication bearer token failed, returning an empty token. Retrieving token from files failed with "Not found: Could not locate the credentials file.". Retrieving token from GCE failed with "Failed precondition: Error executing an HTTP request: libcurl code 6 meaning 'Couldn't resolve host name', error details: Couldn't resolve host 'metadata'".

tensorflow.python.framework.errors_impl.AbortedError: All 10 retry attempts failed. The last failure: Unavailable: Error executing an HTTP request: libcurl code 35 meaning 'SSL connect error', error details: Server aborted the SSL handshake when reading metadata of gs://tfds-data/datasets/glue

**Comment by iftenney** [comment]
This looks like a network error related to https://www.tensorflow.org/datasets. It looks like it's trying to read from a GCS bucket - can you try changing it to `try_gcs=False` on this line? https://github.com/PAIR-code/lit/blob/main/lit_nlp/examples/datasets/glue.py#L21

**Comment by JackyDai1996** [comment]
> This looks like a network error related to https://www.tensorflow.org/datasets. It looks like it's trying to read from a GCS bucket - can you try changing it to `try_gcs=False` on this line? https://github.com/PAIR-code/lit/blob/main/lit_nlp/examples/datasets/glue.py#L21

Thanks a lot! It also turns out that the version of `tensorflow-datasets` is too high so I downgrade it to version `2.1.0` and I change the code as you propose. It finally works out.
