### ISSUE TITLE
dataset in portuguese

### ISSUE THREAD

**Issue by flaviaas23** [PAIR-code/lit#233]
Hello,
I have a dataset in portuguese that I would like to test. I would like to know how can I do that?

Thank you in advance.
Flavia

**Comment by iftenney** [comment]
Hi, there shouldn't be anything different than a regular dataset, as long as all the strings are unicode. Here's an example loader for XNLI: https://github.com/PAIR-code/lit/blob/main/lit_nlp/examples/datasets/classification.py#L63 (and demo launcher: https://github.com/PAIR-code/lit/blob/main/lit_nlp/examples/xnli_demo.py)

**Comment by flaviaas23** [comment]
ok. I'm going to try.
thank you.

**Comment by flaviaas23** [comment]
hello, 
I am running the xnli demo, but doesn't show anything in the 3D graph. It shows the data table but anything else. I don't know if I should do something else . 
I am running loaclly: 
python -m lit_nlp.examples.xnli_demo --port=5432
BR
Flavia

**Comment by iftenney** [comment]
The embedding projector can take a while to load, since it needs to run the model over the whole dataset and then run UMAP on the resulting embeddings. Can you try adding these flags?
```
--warm_start=1.0 --warm_projections
```
This will pre-compute the predictions and UMAP before the server starts - so it'll take a while then, but then the UI should load much faster.

**Comment by flaviaas23** [comment]
I run : 
python -m lit_nlp.examples.xnli_demo --warm_start=1.0 --warm_projections --port=5432
but now the I navigate to localhost:5432 , I got an error message localhost conection was refused
and the last messages I received in console are:
I0225 16:50:53.526144 4376573376 caching.py:226] CachingModelWrapper 'nli': 9960 misses out of 9960 inputs
I0225 16:50:53.526829 4376573376 caching.py:231] Prepared 9960 inputs for model

**Comment by iftenney** [comment]
This is normal - it's running inference on the 9960 examples, which might take a while.
For testing, you can use `--max_examples=50` or similar to limit the size of the dataset, and it should load much faster.

**Comment by flaviaas23** [comment]
thank you !
