### ISSUE TITLE
Custom NER model for LIT

### ISSUE THREAD

**Issue by Stimmot** [PAIR-code/lit#250]
I have a pretrained BERT model for NER and wanted to visualize it using LIT. I cloned the repository and adjusted the simple_pytorch_demo slightly, simply increasing the numbers of labels and providing them in a list:
```
class SimpleSentimentModel(lit_model.Model):
  """Simple sentiment analysis model."""

  LABELS = ["O", "Ort", "Datum",
            "Strafe_Gesamtfreiheitsstrafe_Dauer", "Strafe_Gesamtsatz_Dauer", "Strafe_Gesamtsatz_Betrag",
            "Strafe_Tatbestand",
            "Schadensbetrag",
            "Vorstrafe_nein", "Gestaendnis_ja",
            "straferhoehend_taeter", "strafmildernd_taeter", "Taeter_Drogenbezug_ja"]  # new labels

  def __init__(self, model_name_or_path):
    self.tokenizer = transformers.AutoTokenizer.from_pretrained(
        model_name_or_path)
    model_config = transformers.AutoConfig.from_pretrained(
        model_name_or_path,
        num_labels=13, # number of labels
        output_hidden_states=True,
        output_attentions=True,
    )
```

However, it seems LIT can't completely load the pretrained model. When running it in a console, it says:

```
RuntimeError: Error(s) in loading state_dict for BertForSequenceClassification:
	size mismatch for classifier.weight: copying a param with shape torch.Size([13, 768]) from checkpoint, the shape in current model is torch.Size([2, 768]).
	size mismatch for classifier.bias: copying a param with shape torch.Size([13]) from checkpoint, the shape in current model is torch.Size([2]).
```
It seems to recognize configuration, tokenization etc., but then it fails with this error. I'm happy for any hints on how to solve this.

**Comment by Stimmot** [comment]
It also tells me 
```
I0308 13:37:09.070529 140350438872448 modeling_utils.py:648] loading weights file /home/IAIS/tschmude/bert_remote/examples/token-classification/Data/Models/results_21-01-18_crossval_tests/18.01._cross_val_8_16_5e-5/18-01-2021 (12.47.28)/pytorch_model.bin
I0308 13:37:13.339577 140350438872448 modeling_utils.py:741] Weights of BertForSequenceClassification not initialized from pretrained model: ['bert.pooler.dense.weight', 'bert.pooler.dense.bias']
I0308 13:37:13.339856 140350438872448 modeling_utils.py:747] Weights from pretrained model not used in BertForSequenceClassification: ['bert.embeddings.position_ids']
```
in the error message, maybe that is part of the reason.

**Comment by iftenney** [comment]
For NER, you probably need to use `BertForTokenClassification` to get the correct output head (assuming this is what you trained with?): https://huggingface.co/transformers/model_doc/bert.html#bertfortokenclassification - the `BertForSequenceClassification` is a bit confusingly named, as it only outputs a single score for the sentence (e.g. classification or regression).

**Comment by iftenney** [comment]
We don't have a public NER example yet but we're working on one; in the mean time, you can convert the model output to either `List[str]` (one for each token) and use the `SequenceTags` type, or `List[SpanLabel]` (i, j, label for each entity) and use the `SpanLabels` type - see https://github.com/PAIR-code/lit/blob/main/documentation/development.md#available-types

**Comment by Stimmot** [comment]
Thank you for your replies. I exchanged the SequenceClassification model with the one for TokenClassification -- now it doesn't crash anymore but it still tells me that it won't use the weights from the pretrained model. 
```
I0309 09:38:50.899628 140595424834944 modeling_utils.py:741] Weights of BertForTokenClassification not initialized from pretrained model: ['bert.pooler.dense.weight', 'bert.pooler.dense.bias']
I0309 09:38:50.899801 140595424834944 modeling_utils.py:747] Weights from pretrained model not used in BertForTokenClassification: ['bert.embeddings.position_ids']
```
Does that have to do with converting model output to List[str] or List[SpanLabel]?
Also, I am not quite sure where to perform the type conversion. Do you mean adjusting the model script itself or the pytorch_demo script that receives it?

**Comment by Stimmot** [comment]
I think part of the issue might be that no working version of Cuda is detected:
```
flow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-03-09 15:02:02.935342: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
```
Cuda version 10 is installed, Cuda version 11 however doesn't install due to some cryptic dependency issues. This at least could be why the BERT model doesn't use the weights from the pre-trained model. Is there a way to let model use Cuda version 10?

**Comment by Stimmot** [comment]
So: I solved the CUDA version problem and I asked in the Huggingface forum whether the error message not initialized weights is a problem, it doesn't seem like it.
Still, I don't get any predictions from the model, when the toolkit tries to fetch predictions, it says:
```
I0311 09:23:29.628547 139983866795392 app.py:67] Request received: /get_preds?model=BERT%20NER&dataset_name=NER%20Legal%20texts&requested_types=Scalar
I0311 09:23:29.631730 139983866795392 caching.py:223] CachingModelWrapper 'BERT NER': misses (dataset=NER Legal texts): []
I0311 09:23:29.631817 139983866795392 caching.py:225] CachingModelWrapper 'BERT NER': 0 misses out of 740 inputs
I0311 09:23:29.631881 139983866795392 caching.py:231] Prepared 0 inputs for model
I0311 09:23:29.631950 139983866795392 caching.py:233] Received 0 predictions from model
I0311 09:23:29.632023 139983866795392 app.py:189] Requested types: ['Scalar']
I0311 09:23:29.632117 139983866795392 app.py:199] Will return keys: set()
```
@iftenney do you know what could be the issue?

**Comment by Stimmot** [comment]
I will open up another issue so that problems don't get confused.
