### ISSUE TITLE
Label not configurable

### ISSUE THREAD

**Issue by SHASHANK-PRO-05** [PAIR-code/lit#253]
https://github.com/PAIR-code/lit/blob/a88c58005c3b15694125e15e6165ee5fba7407d0/lit_nlp/components/lime_explainer.py#L120

There should be a configuration parameter which label is being explained using lime text explainer. 

Please refer the doc https://lime-ml.readthedocs.io/en/latest/lime.html#lime.lime_image.LimeImageExplainer.explain_instance in that `labels` arg

**Comment by jameswex** [comment]
Thanks for reaching out! We are tracking this in our internal backlog. We aim to make all interpreters (including our lime explainer) be able to define their configuration options in python, and have the UI render controls for them, and pass the set config parameters back to python when the interpreters are used. We currently have this capability for generator components (like the word replacer counterfactual generator), but not yet for all interpreters.

**Comment by SHASHANK-PRO-05** [comment]
That's fine. But isn't this misleading to the user? because what user is seeing with lime explanations is, explanation of label `1`. 

Right now it is hardcoded to label 1 
https://github.com/PAIR-code/lit/blob/a88c58005c3b15694125e15e6165ee5fba7407d0/lit_nlp/components/lime_explainer.py#L45

There can be n labels here:
https://github.com/PAIR-code/lit/blob/a88c58005c3b15694125e15e6165ee5fba7407d0/lit_nlp/components/lime_explainer.py#L91

At least to begin with the lime explanations, this should be of what label is predicted by model or whatever the true label value is there for instance.

**Comment by jameswex** [comment]
I'll look into adding the config options later this week so that this issue is taken care of

**Comment by OlegDurandin** [comment]
Hi, thank you for your great work.
Currently, In use LIT for multiclass classification and some time don't understood why I get strange explanation. At this moment there is any approach / workaround to choose class, that I'd like to interpret?

**Comment by jameswex** [comment]
I have a fix in flight (for setting configuration options in the UI for saliency methods, such as the class to explain for LIME) that will be available on the "dev" branch as soon as it is fully reviewed and approved.

**Comment by jameswex** [comment]
LIME now has a configurable "class to explain" control as of version 0.3. Note that it currently defaults to 1 (not to the argmax class).

All saliency methods can now define configuration options in python as the config_spec and those options show as controls in the UI, and their settings are passed to the python impl methods in the provided config dict.
