### ISSUE TITLE
Examples for using PyTorch models?

### ISSUE THREAD

**Issue by githubrandomuser2017** [PAIR-code/lit#27]
The LIT documentation says `Framework-agnostic and compatible with TensorFlow, PyTorch, and more,` but I'm having a hard time figuring out what exactly I need to do in order to run a PyTorch model in LIT. To be specific, I would like to use PyTorch models written using the TorchText library and/or the HuggingFace Transformers library.

When I looked through the code in https://github.com/PAIR-code/lit/blob/main/lit_nlp/examples/models/glue_models.py, I see references to `tf.keras` and `tf.GradientTape`, which are obviously for TensorFlow.

Would it be possible for you to please add one or two examples showing how to use PyTorch with LIT?

**Comment by wmmxk** [comment]
There is a package for interpreting pytorch model here: https://captum.ai/tutorials/IMDB_TorchText_Interpret

**Comment by iftenney** [comment]
Yup - we'll release something for this very soon. The existing examples use TensorFlow on the backend, but everything from the `Model` class is returned as NumPy arrays so you can pretty much just replace the TF lines with their PyTorch equivalents.

**Comment by githubrandomuser2017** [comment]
@wmmxk Thank you. That Captum package looks awesome.

**Comment by iftenney** [comment]
Pytorch demo added in #29 - see https://github.com/PAIR-code/lit/blob/main/lit_nlp/examples/simple_pytorch_demo.py
