### ISSUE TITLE
Issues loading tensorflow datasets

### ISSUE THREAD

**Issue by jonsaadfalcon** [PAIR-code/lit#296]
Hello, I was trying to run the first demo model for the GLUE benchmark but I received the following HTTP 403 error code when running the script:

tensorflow_datasets.core.download.downloader.DownloadError: Failed to get url https://firebasestorage.googleapis.com/v0/b/mtl-sentence-representations.appspot.com/o/data%2FSST-2.zip?alt=media&token=aabc5f6b-e466-44a2-b9b4-cf6337f84ac8. HTTP code: 403.

Is there any ways to override the forbidden error?

**Comment by jameswex** [comment]
Sorry about this! Please uninstall tensorflow-datasets pip package and instead install tf-nightly, to fix this.

We're merging the fix for this to the main branch and putting out an updated pip package for LIT this week.

**Comment by jonsaadfalcon** [comment]
> Sorry about this! Please uninstall tensorflow-datasets pip package and instead install tf-nightly, to fix this.
> 
> We're merging the fix for this to the main branch and putting out an updated pip package for LIT this week.

Sounds good, however in the glue.py example script, it still imports tf-datasets as tfds. What should I do to fix this issue?

**Comment by jameswex** [comment]
The code should still work as expected with the tf-nightly package, since it has the same python module names and is built from the same repo, but is built nightly to contain any recent changes (including fixed datasets paths). Let me know if that doesn't work though.

**Comment by jonsaadfalcon** [comment]
> The code should still work as expected with the tf-nightly package, since it has the same python module names and is built from the same repo, but is built nightly to contain any recent changes (including fixed datasets paths). Let me know if that doesn't work though.

I tried running with "import tensorflow as tfds" instead and it gave me errors, specifically:

`AttributeError: module 'tensorflow' has no attribute 'as_numpy'`

**Comment by jameswex** [comment]
Ah sorry, I messed up my instructions. Please keep tensorflow installed (not tf-nightly), but uninstall tensorflow-datasets and replace with tfds-nightly. That will update just the datasets-related code and not require any code changes in LIT.

**Comment by jonsaadfalcon** [comment]
Sounds good, I was able to change the packages but I got the following error:

`ModuleNotFoundError: No module named 'tensorflow.compat'`

**Comment by jameswex** [comment]
What version of tensorflow package do you have installed?

**Comment by jonsaadfalcon** [comment]
I current have tensorflow (2.4.1) installed.

**Comment by jameswex** [comment]
Hmm that is strange. Are you working in a virtual environment? If so, you might want to try creating a new environment and starting the process from scratch. I'm wondering if we messed up the environment somehow with the previous steps tried here.

We just released LIT version 0.3 and now the datasets issue is fixed with the standard install (as we now depend on tfds-nightly instead of tensorflow-datasets), so installing from scratch in a new conda or virtualenv should be successful.

**Comment by jonsaadfalcon** [comment]
I was able to get LIT successfully downloaded and running using virtualenv but I get the following error in the visualization. It seems like none of the datapoints are being visualized:

![image](https://user-images.githubusercontent.com/41205309/113908441-88c56280-97a4-11eb-9cd9-538e8c3e4392.png)

**Comment by jameswex** [comment]
My guess is a transformers library version mismatch. The LIT demos rely on transformers version 4.1.1 as per https://github.com/PAIR-code/lit/blob/main/environment.yml

**Comment by jonsaadfalcon** [comment]
Thank you for the advice. I was able to get it up and running.
