### ISSUE TITLE
[Enhancement] Documentation for install - yarn error

### ISSUE THREAD

**Issue by skyprince999** [PAIR-code/lit#3]
I am setting it up on AWS instance 

- AWS AMI: Deep Learning AMI (Ubuntu 18.04) Version 32.0 - ami-0dc2264cd927ca9eb
- OS: 18.04.2-Ubuntu

`yarn` is not pre-installed and it provides a prompt to install it via `sudo apt install cmdtest`

However doing that leads to the following error:

```
$ yarn && yarn build

ERROR: There are no scenarios; must have at least one
```

This is because Ubuntu picks up the wrong `yarn` version. This is similar to the issue raised [here](https://github.com/yarnpkg/yarn/issues/2821)

I had to remove the `cmdtest` using `autoremove` (_this also removes the dependencies_):
`$ sudo autoremove cmdtest`

and then used the instructions provided here for re-installing `yarn`
https://classic.yarnpkg.com/en/docs/install#debian-stable

```
$ curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -

$ echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list

$ sudo apt update && sudo apt install yarn
```

Submitting this as an _issue_  in case some one gets stuck due to this error

**Comment by jameswex** [comment]
Thanks for this issue and the explanation!

We'll make sure to add more documentation about yarn versions and close this bug once documentation is updated.

@skyprince999 did setting it up on AWS work for you other than that?

**Comment by skyprince999** [comment]
@jameswex  - I have just tried the sample examples, which work fine. 

The only other change I made was change the config settings for the local host in ( `server_flags.py` )
`flags.DEFINE_string('host', '0.0.0.1', 'What host address to serve on.')`

changed it to `0.0.0.0`

**Comment by iftenney** [comment]
Added documentation to server_flags.py in #29 - see https://github.com/PAIR-code/lit/blob/main/lit_nlp/server_flags.py#L39
