### ISSUE TITLE
Formatting datafiles and model

### ISSUE THREAD

**Issue by jonsaadfalcon** [PAIR-code/lit#304]
Hello, I would like to load a Hugging Face transformer along with its dataset. What is the documentation for formatting the transformer as well as the CSV dataset file?

**Comment by iftenney** [comment]
It depends on the task - if you're doing classification, regression, language modeling, or seq2seq, you can likely use one of the existing wrappers we have under [`lit_nlp/examples/models`](https://github.com/PAIR-code/lit/tree/main/lit_nlp/examples/models). For more info on the API, see the docs for (Adding Models and Data](https://github.com/PAIR-code/lit/blob/main/documentation/python_api.md#adding-models-and-data).

(Also note that your data doesn't need to be a CSV - your `Dataset` class can load from any format you like.)

**Comment by jonsaadfalcon** [comment]
I am currently performing a classification task. How can I wrap a BERT Hugging Face model into one of the accepted LIT models? Also, given a CSV, how can I initialize into a Dataset?

**Comment by iftenney** [comment]
For classification you should be able to just use the models in [glue_models.py](https://github.com/PAIR-code/lit/blob/main/lit_nlp/examples/models/glue_models.py#L469); you can make a subclass for a custom task similarly to how we construct them for SST or MNLI:

```python
class MNLIModel(GlueModel):
  """Classification model on MultiNLI."""

  def __init__(self, *args, **kw):
    super().__init__(
        *args,
        text_a_name="premise",
        text_b_name="hypothesis",
        labels=["entailment", "neutral", "contradiction"],
        **kw)
```

For a CSV example, see [here](https://github.com/PAIR-code/lit/blob/main/documentation/python_api.md#datasets).
