### ISSUE TITLE
Demo  not showing Metrics/Perforamnce/Attentions

### ISSUE THREAD

**Issue by thiagosantos1** [PAIR-code/lit#305]
Before actually try the model on my own dataset, I am just playing around the demos and I can't get the Metrics in any of them. 
Is it something about this CachingModelWrapper? 

RUN python -m lit_nlp.examples.glue_demo --port=5432 --quickstart

I get:

Loading model 'sst2-tiny' for task 'sst2' from 'https://storage.googleapis.com/what-if-tool-resources/lit-models/sst2_tiny.tar.gz'
2021-04-08 12:17:04.146657: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-04-08 12:17:04.146830: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
.
.
.
I0408 12:17:10.415369 4721311168 glue_demo.py:125] Dataset: 'sst_dev' with 872 examples
I0408 12:17:10.415554 4721311168 glue_demo.py:127]   truncated to 872 examples
I0408 12:17:10.415620 4721311168 glue_demo.py:125] Dataset: 'stsb_dev' with 1500 examples
I0408 12:17:10.415705 4721311168 glue_demo.py:127]   truncated to 1000 examples
I0408 12:17:10.415756 4721311168 glue_demo.py:125] Dataset: 'mnli_dev' with 9815 examples
I0408 12:17:10.415828 4721311168 glue_demo.py:127]   truncated to 1000 examples
I0408 12:17:10.415879 4721311168 glue_demo.py:125] Dataset: 'mnli_dev_mm' with 9832 examples
I0408 12:17:10.415946 4721311168 glue_demo.py:127]   truncated to 1000 examples
I0408 12:17:10.416290 4721311168 dev_server.py:88] 
.
.
.
I0408 12:17:10.416346 4721311168 dev_server.py:89] Starting LIT server...
I0408 12:17:10.416410 4721311168 caching.py:125] CachingModelWrapper 'sst2-tiny': no cache path specified, not loading.
I0408 12:17:10.416465 4721311168 caching.py:125] CachingModelWrapper 'sst2-small': no cache path specified, not loading.
I0408 12:17:10.416515 4721311168 caching.py:125] CachingModelWrapper 'stsb-tiny': no cache path specified, not loading.
I0408 12:17:10.416570 4721311168 caching.py:125] CachingModelWrapper 'mnli-small': no cache path specified, not loading.
I0408 12:17:10.449529 4721311168 wsgi_serving.py:43] 
.
.
.

I0408 12:17:39.458750 4721311168 app.py:134] 872 of 872 inputs sent as IDs; reconstituting from dataset 'sst_dev'
I0408 12:17:39.459898 4721311168 caching.py:221] CachingModelWrapper 'sst2-tiny': misses (dataset=sst_dev): ['827559828a1681ba9d0d1ec718025cd2', '98d0ff1acb1b1736e8c79fd30ab8a58e', '4f0e2708c7467f14fd7cd703a267cf1d', 'eb90c48a2ebc4bf66e14382739e4d647', 'fcedbabb26d0f144c01847689ff52730', '5cbca5c6b6a27e2678aebda1e7eb1b70', '32ec21d0940f29109e2e72ce9b6aac94', 'a1a90b1d767a59f016bb4cbc7af2b145', 'df3932f52e6925981111126675d88c53', 'cb31a4f739fe4d8581cb12678a406fd9',  ..............]

I0408 12:17:39.461189 4721311168 caching.py:223] CachingModelWrapper 'sst2-tiny': 872 misses out of 872 inputs
I0408 12:17:39.461308 4721311168 caching.py:228] Prepared 872 inputs for model
I0408 12:17:43.540107 4721311168 caching.py:230] Received 872 predictions from model
I0408 12:17:43.541000 4721311168 projection.py:206] Projection request: instance key: frozenset({('field_name', 'cls_emb'), ('dataset_name', 'sst_dev'), ('model_name', 'sst2-tiny'), ('proj_kw', frozenset({('n_components', 3)}))})
I0408 12:17:43.541796 4721311168 caching.py:221] CachingModelWrapper 'sst2-tiny': misses (dataset=sst_dev): []
I0408 12:17:43.541853 4721311168 caching.py:223] CachingModelWrapper 'sst2-tiny': 0 misses out of 872 inputs
I0408 12:17:43.541904 4721311168 caching.py:228] Prepared 0 inputs for model
I0408 12:17:43.541960 4721311168 caching.py:230] Received 0 predictions from model
I0408 12:17:43.542012 4721311168 projection.py:183] Creating new projection instance on 872 points
I0408 12:17:43.542071 4721311168 caching.py:125] CachingModelWrapper 'frozenset({('field_name', 'cls_emb'), ('dataset_name', 'sst_dev'), ('model_name', 'sst2-tiny'), ('proj_kw', frozenset({('n_components', 3)}))})': no cache path specified, not loading.
I0408 12:17:43.543918 4721311168 umap.py:38] UMAP input x_train: (872, 128)
I0408 12:17:50.812697 4721311168 caching.py:221] CachingModelWrapper 'frozenset({('field_name', 'cls_emb'), ('dataset_name', 'sst_dev'), ('model_name', 'sst2-tiny'), ('proj_kw', frozenset({('n_components', 3)}))})': misses (dataset=): []
I0408 12:17:50.812815 4721311168 caching.py:223] CachingModelWrapper 'frozenset({('field_name', 'cls_emb'), ('dataset_name', 'sst_dev'), ('model_name', 'sst2-tiny'), ('proj_kw', frozenset({('n_components', 3)}))})': 0 misses out of 872 inputs
I0408 12:17:50.812869 4721311168 caching.py:228] Prepared 0 inputs for model
I0408 12:17:50.812924 4721311168 caching.py:230] Received 0 predictions from model
I0408 12:17:50.815813 4721311168 _internal.py:113] 127.0.0.1 - - [08/Apr/2021 12:17:50] "POST /get_interpretations?model=sst2-tiny&dataset_name=sst_dev&interpreter=umap HTTP/1.1" 200 -
I0408 12:17:50.816690 4721311168 app.py:134] 872 of 872 inputs sent as IDs; reconstituting from dataset 'sst_dev'
I0408 12:17:50.817753 4721311168 caching.py:221] CachingModelWrapper 'sst2-tiny': misses (dataset=sst_dev): []
I0408 12:17:50.817823 4721311168 caching.py:223] CachingModelWrapper 'sst2-tiny': 0 misses out of 872 inputs
I0408 12:17:50.817871 4721311168 caching.py:228] Prepared 0 inputs for model
I0408 12:17:50.817926 4721311168 caching.py:230] Received 0 predictions from model
I0408 12:17:50.817981 4721311168 app.py:181] Requested types: ['MulticlassPreds']
I0408 12:17:50.818044 4721311168 app.py:191] Will return keys: {'probas'}
I0408 12:17:50.821425 4721311168 _internal.py:113] 127.0.0.1 - - [08/Apr/2021 12:17:50] "POST /get_preds?model=sst2-tiny&dataset_name=sst_dev&requested_types=MulticlassPreds HTTP/1.1" 200 -
I0408 12:17:50.822339 4721311168 app.py:134] 872 of 872 inputs sent as IDs; reconstituting from dataset 'sst_dev'
I0408 12:17:50.823351 4721311168 caching.py:221] CachingModelWrapper 'sst2-tiny': misses (dataset=sst_dev): []
I0408 12:17:50.823419 4721311168 caching.py:223] CachingModelWrapper 'sst2-tiny': 0 misses out of 872 inputs
I0408 12:17:50.823467 4721311168 caching.py:228] Prepared 0 inputs for model
I0408 12:17:50.823568 4721311168 caching.py:230] Received 0 predictions from model
I0408 12:17:50.833844 4721311168 _internal.py:113] 127.0.0.1 - - [08/Apr/2021 12:17:50] "POST /get_interpretations?model=sst2-tiny&dataset_name=sst_dev&interpreter=metrics HTTP/1.1" 200 -
I0408 12:17:50.835066 4721311168 app.py:134] 872 of 872 inputs sent as IDs; reconstituting from dataset 'sst_dev'
I0408 12:17:50.836047 4721311168 caching.py:221] CachingModelWrapper 'sst2-tiny': misses (dataset=sst_dev): []
I0408 12:17:50.836122 4721311168 caching.py:223] CachingModelWrapper 'sst2-tiny': 0 misses out of 872 inputs
I0408 12:17:50.836179 4721311168 caching.py:228] Prepared 0 inputs for model
I0408 12:17:50.836241 4721311168 caching.py:230] Received 0 predictions from model
I0408 12:17:50.836321 4721311168 app.py:181] Requested types: ['MulticlassPreds']
I0408 12:17:50.836395 4721311168 app.py:191] Will return keys: {'probas'}
I0408 12:17:50.840148 4721311168 _internal.py:113] 127.0.0.1 - - [08/Apr/2021 12:17:50] "POST /get_preds?model=sst2-tiny&dataset_name=sst_dev&requested_types=MulticlassPreds HTTP/1.1" 200 -
I0408 12:17:50.841331 4721311168 app.py:134] 872 of 872 inputs sent as IDs; reconstituting from dataset 'sst_dev'
I0408 12:17:50.842397 4721311168 caching.py:221] CachingModelWrapper 'sst2-tiny': misses (dataset=sst_dev): []
I0408 12:17:50.842478 4721311168 caching.py:223] CachingModelWrapper 'sst2-tiny': 0 misses out of 872 inputs
I0408 12:17:50.842532 4721311168 caching.py:228] Prepared 0 inputs for model
I0408 12:17:50.842595 4721311168 caching.py:230] Received 0 predictions from model
I0408 12:17:50.851847 4721311168 _internal.py:113] 127.0.0.1 - - [08/Apr/2021 12:17:50] "POST /get_interpretations?model=sst2-tiny&dataset_name=sst_dev&interpreter=metrics HTTP/1.1" 200 -
I0408 12:17:50.853083 4721311168 app.py:134] 872 of 872 inputs sent as IDs; reconstituting from dataset 'sst_dev'
I0408 12:17:50.854034 4721311168 caching.py:221] CachingModelWrapper 'sst2-tiny': misses (dataset=sst_dev): []
I0408 12:17:50.854104 4721311168 caching.py:223] CachingModelWrapper 'sst2-tiny': 0 misses out of 872 inputs
I0408 12:17:50.854152 4721311168 caching.py:228] Prepared 0 inputs for model
I0408 12:17:50.854213 4721311168 caching.py:230] Received 0 predictions from model
I0408 12:17:50.854276 4721311168 app.py:181] Requested types: ['MulticlassPreds']
I0408 12:17:50.854346 4721311168 app.py:191] Will return keys: {'probas'}
I0408 12:17:50.858346 4721311168 _internal.py:113] 127.0.0.1 - - [08/Apr/2021 12:17:50] "POST /get_preds?model=sst2-tiny&dataset_name=sst_dev&requested_types=MulticlassPreds HTTP/1.1" 200 -
I0408 12:17:50.859359 4721311168 app.py:134] 872 of 872 inputs sent as IDs; reconstituting from dataset 'sst_dev'
I0408 12:17:50.860310 4721311168 caching.py:221] CachingModelWrapper 'sst2-tiny': misses (dataset=sst_dev): []
I0408 12:17:50.860367 4721311168 caching.py:223] CachingModelWrapper 'sst2-tiny': 0 misses out of 872 inputs
I0408 12:17:50.860417 4721311168 caching.py:228] Prepared 0 inputs for model
I0408 12:17:50.860478 4721311168 caching.py:230] Received 0 predictions from model
I0408 12:17:50.860539 4721311168 app.py:181] Requested types: ['MulticlassPreds']
I0408 12:17:50.860692 4721311168 app.py:191] Will return keys: {'probas'}
I0408 12:17:50.864442 4721311168 _internal.py:113] 127.0.0.1 - - [08/Apr/2021 12:17:50] "POST /get_preds?model=sst2-tiny&dataset_name=sst_dev&requested_types=MulticlassPreds HTTP/1.1" 200 -
I0408 12:17:50.865351 4721311168 app.py:134] 872 of 872 inputs sent as IDs; reconstituting from dataset 'sst_dev'
I0408 12:17:50.866220 4721311168 caching.py:221] CachingModelWrapper 'sst2-tiny': misses (dataset=sst_dev): []
I0408 12:17:50.866277 4721311168 caching.py:223] CachingModelWrapper 'sst2-tiny': 0 misses out of 872 inputs
I0408 12:17:50.866323 4721311168 caching.py:228] Prepared 0 inputs for model
I0408 12:17:50.866379 4721311168 caching.py:230] Received 0 predictions from model
I0408 12:17:50.866438 4721311168 app.py:181] Requested types: ['RegressionScore']
I0408 12:17:50.866503 4721311168 app.py:191] Will return keys: set()
I0408 12:17:50.867934 4721311168 _internal.py:113] 127.0.0.1 - - [08/Apr/2021 12:17:50] "POST /get_preds?model=sst2-tiny&dataset_name=sst_dev&requested_types=RegressionScore HTTP/1.1" 200 -
I0408 12:17:50.868768 4721311168 app.py:134] 872 of 872 inputs sent as IDs; reconstituting from dataset 'sst_dev'
I0408 12:17:50.869621 4721311168 caching.py:221] CachingModelWrapper 'sst2-tiny': misses (dataset=sst_dev): []
I0408 12:17:50.869680 4721311168 caching.py:223] CachingModelWrapper 'sst2-tiny': 0 misses out of 872 inputs
I0408 12:17:50.869728 4721311168 caching.py:228] Prepared 0 inputs for model
I0408 12:17:50.869785 4721311168 caching.py:230] Received 0 predictions from model
I0408 12:17:50.869843 4721311168 app.py:181] Requested types: ['Scalar']
I0408 12:17:50.869925 4721311168 app.py:191] Will return keys: set()
I0408 12:17:50.871339 4721311168 _internal.py:113] 127.0.0.1 - - [08/Apr/2021 12:17:50] "POST /get_preds?model=sst2-tiny&dataset_name=sst_dev&requested_types=Scalar HTTP/1.1" 200 -

![image](https://user-images.githubusercontent.com/15396707/114062105-bf5eb400-985c-11eb-91e3-23e8b8cd12e0.png)

**Comment by jameswex** [comment]
Nothing from the command line logs there look suspect.

Do the other modules in the lower section work? I don't see the confusion matrix module down there either. How about the other tabs of the lower section?

What is your dev environment and the versions of the code and its dependencies you are using?

**Comment by thiagosantos1** [comment]
No, None of the modules in the lower section seems to work. 
I am trying the demo in both ways as illustrated on the demo page (https://pair-code.github.io/lit/setup/ ). In both cases, I am using environment.yml to install all dependencies
- pip install lit-nlp
- clone the repository and install

What dependencies are used for loading the modules in the lower section? Everything else seems to work fine. Once launched, it does gets the message: "Fetching Projections". Once it's "done", it just doesn't show anything.

I0408 13:19:51.620254 4466851264 caching.py:223] CachingModelWrapper 'bert-base-uncased': 872 misses out of 872 inputs
I0408 13:19:51.620362 4466851264 caching.py:228] Prepared 872 inputs for model
I0408 13:20:59.977128 4466851264 caching.py:230] Received 872 predictions from model

I0408 13:20:59.978108 4466851264 projection.py:206] Projection request: instance key: frozenset({('dataset_name', 'sst_dev'), ('model_name', 'bert-base-uncased'), ('proj_kw', frozenset({('n_components', 3)})), ('field_name', 'cls_emb')})
I0408 13:20:59.978914 4466851264 caching.py:221] CachingModelWrapper 'bert-base-uncased': misses (dataset=sst_dev): []
I0408 13:20:59.978972 4466851264 caching.py:223] CachingModelWrapper 'bert-base-uncased': 0 misses out of 872 inputs
I0408 13:20:59.979022 4466851264 caching.py:228] Prepared 0 inputs for model
I0408 13:20:59.979076 4466851264 caching.py:230] Received 0 predictions from model
I0408 13:20:59.979130 4466851264 projection.py:183] Creating new projection instance on 872 points
I0408 13:20:59.979187 4466851264 caching.py:125] CachingModelWrapper 'frozenset({('dataset_name', 'sst_dev'), ('model_name', 'bert-base-uncased'), ('proj_kw', frozenset({('n_components', 3)})), ('field_name', 'cls_emb')})': no cache path specified, not loading.
I0408 13:20:59.987919 4466851264 umap.py:38] UMAP input x_train: (872, 768)
I0408 13:21:07.276393 4466851264 caching.py:221] CachingModelWrapper 'frozenset({('dataset_name', 'sst_dev'), ('model_name', 'bert-base-uncased'), ('proj_kw', frozenset({('n_components', 3)})), ('field_name', 'cls_emb')})': misses (dataset=): []
I0408 13:21:07.276504 4466851264 caching.py:223] CachingModelWrapper 'frozenset({('dataset_name', 'sst_dev'), ('model_name', 'bert-base-uncased'), ('proj_kw', frozenset({('n_components', 3)})), ('field_name', 'cls_emb')})': 0 misses out of 872 inputs
I0408 13:21:07.276552 4466851264 caching.py:228] Prepared 0 inputs for model
I0408 13:21:07.276607 4466851264 caching.py:230] Received 0 predictions from model
I0408 13:21:07.279385 4466851264 _internal.py:113] 127.0.0.1 - - [08/Apr/2021 13:21:07] "POST /get_interpretations?model=bert-base-uncased&dataset_name=sst_dev&interpreter=umap HTTP/1.1" 200 -

**Comment by jameswex** [comment]
Thanks for the details, that helps. There are no dependency issues that should cause only the modules in the lower section to not appear. I've never seen LIT behave that way before.

What OS and browser are you using? The screenshot makes it seem like for some reason the bottom panel is being rendered with height 0. Perhaps the modules are there but aren't being rendered correctly.

**Comment by thiagosantos1** [comment]
Very interesting indeed. You were right, it was there, but just with height 0(for some reason). I am using macOS Catalina 10.15.17 and Chrome 89.0.4389.82. Changed to Safari and it worked perfectly. 

Thanks a lot for your help
