### ISSUE TITLE
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='firebasestorage.googleapis.com', port=443): Max retries exceeded with url: /v0/b/mtl-sentence-represe ntations.appspot.com/o/data%2FSST-2.zip?alt=media&token=aabc5f6b-e466-44a2-b9b4-cf6337f84ac8 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnect ion object at 0x000001F9B4D7E1D0>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))

### ISSUE THREAD

**Issue by sxd-max** [PAIR-code/lit#340]
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='firebasestorage.googleapis.com', port=443): Max retries exceeded with url: /v0/b/mtl-sentence-represe
ntations.appspot.com/o/data%2FSST-2.zip?alt=media&token=aabc5f6b-e466-44a2-b9b4-cf6337f84ac8 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnect
ion object at 0x000001F9B4D7E1D0>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))

**Comment by jameswex** [comment]
Not sure what these errors are in relation to. Please add more details to what you attempted and what happened. Thanks.
