### ISSUE TITLE
Seq2seq NMT

### ISSUE THREAD

**Issue by shahrukh357** [PAIR-code/lit#35]
I did not find the support for seq2seq model (like NMT) in the pretrained_lm_demo.py file. It seems that only "bert-" and "gpt2" are supported for now. Am I right?

**Comment by jameswex** [comment]
Thanks for reaching out! We will be adding a seq2seq example shortly. We're just cleaning up the code (see #10). We'll close this issue once its in the repo.

**Comment by YKX-A** [comment]
Looking forward to your work🙃 (t5 and seq2seq)

**Comment by iftenney** [comment]
T5 seq2seq example, for summarization task: https://github.com/PAIR-code/lit/blob/main/lit_nlp/examples/t5_summarization_demo.py
