### ISSUE TITLE
UMAP Error

### ISSUE THREAD

**Issue by shahrukh357** [PAIR-code/lit#36]
Earlier there was no error like the below one 

"AttributeError: module 'umap' has no attribute 'UMAP'."

But After the recent update  which was made 3 days ago to the repo.
![umap_issuse](https://user-images.githubusercontent.com/37707810/92324944-1ea8db80-f064-11ea-930a-2fd3555edfe5.png)

**Comment by jameswex** [comment]
What version of umap-learn do you have installed in your python environment?
