### ISSUE TITLE
Can I use a saved checkpoint of a fine-tuned BERT model (through PyTorch Lightning & Huggingface/Transformers) with LIT?

### ISSUE THREAD

**Issue by starterfish** [PAIR-code/lit#444]
My understanding from the documentation is that I need to define my own dataset and model objects. Following simply_pytorch_demo.py, I'm not entirely sure how I'd replace the SimpleSentimentModel class with the binary classifier model that I've built using PyTorch Lightning and Transformers. 

Also, Line 52 of that file looks for your model path:
```
flags.DEFINE_string(
    "model_path",
    "https://storage.googleapis.com/what-if-tool-resources/lit-models/sst2_tiny.tar.gz",
    "Path to trained model, in standard transformers format, e.g. as "
    "saved by model.save_pretrained() and tokenizer.save_pretrained()")
```
My model was fitted using PyTorch Lightning's Trainer class, and thus my model.save_pretrained() is actually a trainer.save_checkpoint(). I can then load the model with a model.load_from_checkpoint().

Reading the other issues on here, it also sounds like LIT can accept a variety of formats for the dataset. The data themselves are formatted into a PyTorch Dataset object. 
```
class ToxicCommentsDataset(Dataset):

  def __init__(
    self, 
    data: pd.DataFrame, 
    tokenizer: BertTokenizer, 
    max_token_len: int = maximum_tokens_allowed
  ):
    self.tokenizer = tokenizer
    self.data = data
    self.max_token_len = max_token_len
    
  def __len__(self):
    return len(self.data)

  def __getitem__(self, index: int):
    data_row = self.data.iloc[index]
    comment_text = data_row.content_clean
    labels = torch.tensor(data_row.label_data, dtype=torch.float)

    encoding = self.tokenizer.encode_plus(
      comment_text,
      add_special_tokens=True,
      max_length=self.max_token_len,
      return_token_type_ids=False,
      padding="max_length",
      truncation=True,
      return_attention_mask=True,
      return_tensors='pt',
    )

    return dict(
      comment_text=comment_text,
      input_ids=encoding["input_ids"].flatten(),
      attention_mask=encoding["attention_mask"].flatten(),
      labels=labels
    )
```

Inputs are fed into the BERT model with a PyTorch Lightning DataModule object. The DataModule takes the training, validation, and test data as separate PyTorch Dataloaders:

```
class ToxicCommentDataModule(pl.LightningDataModule):

  def __init__(self, train_df, test_df, tokenizer, batch_size=6, max_token_len=maximum_tokens_allowed):
    super().__init__()
    self.batch_size = batch_size
    self.train_df = train_df
    self.test_df = test_df
    self.tokenizer = tokenizer
    self.max_token_len = max_token_len

  def setup(self, stage=None):
    self.train_dataset = ToxicCommentsDataset(
      self.train_df,
      self.tokenizer,
      self.max_token_len
    )

    self.test_dataset = ToxicCommentsDataset(
      self.test_df,
      self.tokenizer,
      self.max_token_len
    )

  def train_dataloader(self):
    return DataLoader(
      self.train_dataset,
      batch_size=self.batch_size,
      shuffle=True,
      num_workers=0
    )

  def val_dataloader(self):
    return DataLoader(
      self.test_dataset,
      batch_size=self.batch_size,
      num_workers=0
    )

  def test_dataloader(self):
    return DataLoader(
      self.test_dataset,
      batch_size=self.batch_size,
      num_workers=0
    )
```

I then create the BERT classifier as a PyTorch Lightning LightningModule object, whose output is predicted probability of the positive class.

Any help you could provide is greatly appreciated. Sorry if it's too much / too little detail; I'm not great at this stuff so just trying to get set in the right direction.

**Comment by jameswex** [comment]
https://pair-code.github.io/lit/setup/ contains some details.

For the Dataset object, you need to load your entire dataset to analyze into a list of dict objects, in the self._examples data member. You can use any approach you like to do that loading.

For the Model object, you need to write a predict_minibatch method that takes a list of dicts just like the one you loaded in the Dataset object, and runs your model and returns a list of dicts of the returns from the model. In your Model classes constructor, you can use model.load_from_checkpoint() or any other approach you like to load your model. You don't need to follow what we've done in our examples for implementation details.
