### ISSUE TITLE
400 error: Path is not safe

### ISSUE THREAD

**Issue by andrewschreiber** [PAIR-code/lit#48]
I get this error after running the demo command `python -m lit_nlp.examples.quickstart_sst_demo --port=5432`. I am able to complete training, but when I open up localhost:5432 I see this:

![image](https://user-images.githubusercontent.com/1892071/93137890-0869d380-f693-11ea-8c2d-2cc0abb14cde.png)

Here is where the error is triggered (defined later in the file too): https://github.com/PAIR-code/lit/blob/437df8d5907efe6c1ebb10ef2a161d2749aa3522/lit_nlp/lib/wsgi_app.py#L136

**Comment by andrewschreiber** [comment]
Check path is safe (stays within current directory).
    This is for preventing directory-traversal attacks.
    Args:
      path: The path to check for safety.
    Returns:
      True if the given path stays within the current directory, and false
      if it would escape to a higher directory. E.g. _path_is_safe('index.html')
      returns true, but _path_is_safe('../../../etc/password') returns false.

**Comment by jameswex** [comment]
Thanks for reaching out. From what directory are you running the python command to launch the demo? It may be due to not running the demo from a parent directory of where the demo was installed.

**Comment by andrewschreiber** [comment]
I was running from the root project directory (~/git/lit) in my case. 

I wound up building from source, and the tool is now working. Will try the parent directory approach if I go back to using the PyPI package.

**Comment by jameswex** [comment]
Thanks. The pip package is new and its possible we will need to update the PathIsSafe code to account for where the code would live when pip-installed.

**Comment by YokoHono** [comment]
I encountered the same error when I tried to run my own demo. Copying the 'lit_nlp' folder into the folder from where I want to run demo.py worked for me.

**Comment by lstsq** [comment]
```bash
# Ubuntu 18.04

cd /usr/local/lib/python3.7/dist-packages
```

**Comment by lagph** [comment]
> Thanks. The pip package is new and its possible we will need to update the PathIsSafe code to account for where the code would live when pip-installed.

This sounds good, I think users will expect to be able to pip install and write a script to spin up the server from within a project.

**Comment by jameswex** [comment]
Will be fixed by #149
