### ISSUE TITLE
Tensorboard / Jupyter plugin

### ISSUE THREAD

**Issue by andrewschreiber** [PAIR-code/lit#49]
Is there a plan to integrate Lit with Tensorboard or Jupyter like the What-If tool?

**Comment by jameswex** [comment]
Thanks for reaching out. We are planning on looking into LIT being usable as a notebook plugin (colab and/or jupyter). TensorBoard could also be a possibility but I think we would first look at the notebook extension version.

**Comment by jameswex** [comment]
LIT is now usable in colab and jupyter as of version 0.3. Check it out! See a demo linked in the project readme and on the LIT website demo page.
