### ISSUE TITLE
UMAP visualization in-between Transformer layers

### ISSUE THREAD

**Issue by LittlePea13** [PAIR-code/lit#51]
To better understand how the network encodes information, it is not only interesting to see the resulting hidden representations before classifying (as shown now in the PCA/UMAP visualization) but also how it changes between layers.

I feel it would be interesting to be able to choose which layer to visualize in the PCA/UMAP window, perhaps using a dropdown selection. The models already output these hidden representations so it would be a matter of recomputing the PCA/UMAP when another layer is selected.

I could help implement this in a new branch if you think it would be worth adding.

And thanks again for the tool :)

**Comment by iftenney** [comment]
You can! There's a dropdown to select which embedding field to visualize, and it'll automatically compute the projection if it's not cached.
![Screenshot from 2020-10-29 21-51-57](https://user-images.githubusercontent.com/2609401/97661282-2a47cb80-1a31-11eb-9ce9-31c5e1f6d99d.png)

The default glue models just return the output layer [CLS] embedding, but you can easily add more `Embedding()` fields to the spec. If you want the [CLS] token for each layer, or to pool over some other set of indices, `embs` here is a list of the activations of each layer: https://github.com/PAIR-code/lit/blob/main/lit_nlp/examples/models/glue_models.py#L360
