### ISSUE TITLE
How to save salience maps for all sentences at once

### ISSUE THREAD

**Issue by JackyDai1996** [PAIR-code/lit#56]
Hi!

I would like to save and export the salience maps for all of the sentences at once, rather than one click at a time. Is there a convenient way to do so? Thx.

**Comment by jameswex** [comment]
Thanks for reaching out. We don't currently have a way to view all salience maps at once in the tool, but I can see why this would be valuable.

Are you looking to view them all and save the images, or are you trying to save the token-wise salience values for each token in each input for use outside the tool?

**Comment by JackyDai1996** [comment]
> Thanks for reaching out. We don't currently have a way to view all salience maps at once in the tool, but I can see why this would be valuable.
> 
> Are you looking to view them all and save the images, or are you trying to save the token-wise salience values for each token in each input for use outside the tool?

Yes, I am trying to realize the latter so that I can see which tokens have the most salience values in each input.

**Comment by iftenney** [comment]
We don't have a good way of exporting this directly from the UI, but if you want you can easily use the salience mappers in a notebook or a stand-alone script. Something like this will work without requiring you to start a LIT server:
```python
dataset = SSTData(...)
model = SentimentModel(...)
lime = lime_explainer.LIME()
lime.run([dataset.examples[0]],
model, dataset)
```
