### ISSUE TITLE
Adapt other demos for Docker

### ISSUE THREAD

**Issue by argideritzalpea** [PAIR-code/lit#564]
I am attempting to run the [quickstart_sst_demo.py](https://github.com/PAIR-code/lit/blob/main/lit_nlp/examples/quickstart_sst_demo.py) via the [Dockerfile](https://github.com/PAIR-code/lit/blob/main/Dockerfile) that is initially set up to run the [lm_demo.py](https://github.com/PAIR-code/lit/blob/main/lit_nlp/examples/lm_demo.py).

I modify the Dockerfile to point to the quickstart_sst_demo by changing line 6 to:
`ENV APP_COMMAND "lit_nlp.examples.quickstart_sst_demo:get_wsgi_app()"`  and copied the function `get_wsgi_app()` from `lm_demo.py` into the `quickstart_sst_demo.py`, hoping that it be referenced.

However, upon running the command `gunicorn -c lit_nlp/examples/gunicorn_config.py $APP_COMMAND` (and after the `quickstart_sst_demo` runs,  I receive the following error that kills the server:
`Failed to find application object: 'get_wsgi_app()'`

Can anyone advise as to how to get gunicorn server to run for the other demos? Thank you.

**Comment by RyanMullins** [comment]
Hi @argideritzalpea, thanks for your interest in LIT!

`gunicorn` expects all `get_wsgi_app()` functions to return a `LitApp` instance that it can launch, and the `get_wsgi_app()` gets this as the return from `main()`. Unfortunately, we only have `main()` return a `LitApp` for a small subset of our demos (those that we host as examples from our public website) and `quickstart_sst_demo` is not one of those, so you'll need to add a `return` statement to the last line of the `main()` function.

Copy and paste the following code into `quickstart_sst_demo.py`, rebuild your docker image, and run a container from that image and everything should work. Please let me know if you are successful and I will mark this issue as resolved. 

```python
def get_wsgi_app():
  FLAGS.set_default("server_type", "external")
  FLAGS.set_default("demo_mode", True)
  # Parse flags without calling app.run(main), to avoid conflict with
  # gunicorn command line flags.
  unused = flags.FLAGS(sys.argv, known_only=True)
  return main(unused)

def main(_):
  model_path = FLAGS.model_path or tempfile.mkdtemp()
  logging.info("Working directory: %s", model_path)
  run_finetuning(model_path)

  # Load our trained model.
  models = {"sst": glue_models.SST2Model(model_path)}
  datasets = {"sst_dev": glue.SST2Data("validation")}

  # Start the LIT server. See server_flags.py for server options.
  lit_demo = dev_server.Server(models, datasets, **server_flags.get_flags())
  return lit_demo.serve()
```

**Comment by argideritzalpea** [comment]
This cleared up the issue - thank you!
