### ISSUE TITLE
Support for additional model types

### ISSUE THREAD

**Issue by berbertranslit** [PAIR-code/lit#569]
This is a feature request for support for additional models, such as Longformer, for long documents. It would be great to use the LIT fine-tuning scripts for longer pieces of text (4096 tokens).

**Comment by iftenney** [comment]
We don't have a demo with these currently, but you can easily use LIT with your own model class: https://github.com/PAIR-code/lit/wiki/api.md#models

If the models are available in HuggingFace (looks like Longformer is: https://huggingface.co/transformers/model_doc/longformer.html), the code for this will probably be pretty similar to the existing BERT/GPT/T5 demos.
