### ISSUE TITLE
How add a custom projector?

### ISSUE THREAD

**Issue by krlng** [PAIR-code/lit#601]
Hello,

I love the idea of the lit tool and start working with it a lot. Currently I am missing some more detailed documentation on how to customize the tool to own needs, so I am going to ask a couple of questions here, I hope this is fine.

I would like to have an UMAP projection to only two dimensions. How would I add such an additional projection into LIT?

**Comment by jameswex** [comment]
Right now we don't offer great support for customizing the embedding projector. There are a few options, all of which will require you to make code changes in LIT and rebuild. The simplest, if you just want to replace 3d UMAP with 2d UMAP, is to edit embeddings_module.ts, changing `'n_components': 3` to `'n_components': 2`, and recompiling the front-end code as per the `yarn` commands at https://github.com/PAIR-code/lit#install-from-source

**Comment by krlng** [comment]
Thanks, I will try sometime. How ever I was hoping this could be adapted similiar to the layout components.
