### ISSUE TITLE
Dataset UI does not support scrolling on many features

### ISSUE THREAD

**Issue by krlng** [PAIR-code/lit#604]
Currently the UI of a dataset is fixed in height (there would be more features then those visible):

<img width="1073" alt="Screenshot 2021-12-31 at 14 28 25" src="https://user-images.githubusercontent.com/1107509/147825732-3c82f116-b189-4762-8ae2-6256e8750e66.png">

This is especially bad, when you have multiple models and datasets, because below those features it would show which datasets are compatible with which models, but that one than get quickly not visible anymore.

**Comment by jameswex** [comment]
Thanks @krlng . Should be a simple fix and we'll get it fixed on our 'dev' branch as soon as someone on LIT can pick up the task.

**Comment by jameswex** [comment]
Fixed on dev branch in https://github.com/PAIR-code/lit/commit/f66c1b37b66730615c5d1d2b1471afe2d014777c

You can see this fix if you build LIT yourself from the dev branch and it will be included in our next release.
