### ISSUE TITLE
Can this work with Sci-kit SVM?

### ISSUE THREAD

**Issue by tburleyinfo** [PAIR-code/lit#62]
We were wondering if we can save an SVM model and use it here or does it only work with Language Models and neural models with pytorch/tensorflow? 

Thank you in advance.

**Comment by jameswex** [comment]
Thanks for reaching out. Nothing should stop you from using LIT with an SVM model. To use LIT with your own model/dataset, you just need to define what information is in the dataset, and what the model inputs and outputs are. See https://github.com/PAIR-code/lit/blob/main/docs/python_api.md#adding-models-and-data for more details. The models don't need to be neural networks, or use any specific framework. As long as you can call into the model to perform prediction using python (or even use python to call a server that does the model prediction), then you can use LIT.

What are the input features and outputs of the model you want to analyze?

**Comment by tburleyinfo** [comment]
Ok. So we've trained a few SVMs as binary text classifiers. A single input would be a news article + metadata like the publication date and document ID, and the prediction would be a simple yes or no.
