### ISSUE TITLE
[GSOC] Tutorials for Working with Interpretable/Explainable AI with LIT

### ISSUE THREAD

**Issue by RyanMullins** [PAIR-code/lit#664]
# Full Project

LIT is a platform for visualizing and understanding AI/ML models. The complexity of LIT's interface and the models that it supports can impose barriers and obstacles to adoption. 

We are looking for help in expanding the [tutorials](https://pair-code.github.io/lit/tutorials/) on the LIT website in the following categories with some suggestions for focus areas:

- **Walk-Throughs** of workflows for analyzing models;
    - Making sense of results across interpretability techniques
        - Grad L2 Norm, Grad⋅Input, Integrated Gradients, LIME
    - Using generators to explore counterfactual predictions, and comparing predictions.
    - Using our [wrapper](https://github.com/PAIR-code/lit/blob/main/lit_nlp/examples/stanza_demo.py) for Stanford's [Stanza](https://stanfordnlp.github.io/stanza/) toolkit, and enhancing it with new features.
- **How-Tos** for using specific LIT modules and features; and
    - Identifying influential features in the Feature Attribution module
    - Finding planted examples with the Salience Clustering module
    - Making sense of interpretability results in the Salience Maps module
    - Making sense of connections in the Attention visualization
    - Using LIT to analyze tabular models a-la the [What-If Tool](https://pair-code.github.io/what-if-tool/).
- **Tips and Tricks** for using LIT in non-standard workflows
    - Effective and efficient integration with Colab and/or Jupyter
    - Adding custom metrics to the Metrics module
    - Developing new interpretability or generator components

Please feel free to suggest your own focus area in your applications!

# Starter Project

Given the emphasis on technical writing for this project, please create and submit a brief (not more than 500 words) **How-To** write-up for one of the following LIT features: 

Referencing our [classification demo](https://pair-code.github.io/lit/demos/glue.html): Confusion Matrix, Embeddings, or Metrics.
Referencing our [gender bias demo](https://pair-code.github.io/lit/demos/coref.html): Structured Predictions, or Data Table.

**Comment by soma2000-lang** [comment]
@RyanMullins  I am working on this issue

**Comment by RyanMullins** [comment]
The LIT team requires that all applications related to this topic include a link to your completed starter project for us to review (along with the standard [GSoC application requirements](https://summerofcode.withgoogle.com/how-it-works)). As such, we will not be assigning this issue to anyone because everyone interested must complete it in order to be considered.

Thanks to those who have commented, reacted, etc. for your interest. Looking forward to reviewing your applications!

**Comment by abdimoh** [comment]
> The LIT team requires that all applications related to this topic include a link to your completed starter project for us to review (along with the standard [GSoC application requirements](https://summerofcode.withgoogle.com/how-it-works)). As such, we will not be assigning this issue to anyone because everyone interested must complete it in order to be considered.
> 
> Thanks to those who have commented, reacted, etc. for your interest. Looking forward to reviewing your applications!

Thanks for the clarification, Ryan!

**Comment by Devansh-0** [comment]
Hi, I needed a little clarification on the task. Do we have to explain the working and the execution of the LIT features? 
For example, for confusion matrix, should I explain what it is and how to assess the results based on it?

**Comment by RyanMullins** [comment]
Hi @Devansh-0,

Yes, that's exactly what we're looking for for these starter projects. 

Assume your target audience is a class of college students, perhaps this is their first course in stats or ML concepts. How you would explain your chosen module to those students? What does the module help them understand? What are the module's visual components and controls? How do you to use it find meaning in a model's predictions? Does the way you use it change if you're looking at one datapoint, a small set of datapoints, or the entire dataset? Try to provide a concrete example to illustrate these nuances.

The [UI Guide](https://github.com/PAIR-code/lit/wiki/ui_guide.md#module-details) has some very basic explanations of the "what it is" portion for most of the Modules listed that applicants can build on.

**Comment by Devansh-0** [comment]
Understood. 
Thank you, Ryan!

**Comment by vibhorjain08** [comment]
Hey so do I need to write a How to use confusion matrix brief or a how to use LIT for confusion matrix brief? (basically practical implementation vs theoretical understanding, what is expected out of me to write on?)

**Comment by RyanMullins** [comment]
The application window for GSoC 2022 open today (4 Apr 2022)! Thanks to those who have reached out here, via email, etc. for you interest in this topic. I'm able to provide one round of feedback on proposals and starter projects until 15 Apr 2022. 

To received feedback:

1. Submit all content required for your starter task via a Google Doc or GitHub Gist
2. Reply to this thread and @ me (or send me an email) with a link to the Doc/Gist

**Comment by soma2000-lang** [comment]
@RyanMullins  Can you please share your email-id to share the  link of the Google doc (proposal)

**Comment by RyanMullins** [comment]
Same username as here, but @google.com

Sorry for being cagy, but trying to minimize spam potential.

**Comment by soma2000-lang** [comment]
@RyanMullins I have sent the proposal at your email id.Kindly check.

**Comment by animeshokhade** [comment]
@RyanMullins @mpushkarna I have shared the proposal doc with you. I'll also be submitting my proposal today. Please provide feedback so that I can update my proposal accordingly.

**Comment by Abdelrahmanrezk** [comment]
Hello @RyanMullins , should we write the explanation based on LIT, or the idea in general ?

**Comment by Abdelrahmanrezk** [comment]
Hey @RyanMullins , I have sent you an email with the starter project about the Embedding in the LIT.
Please let me know if you can find it or not, as well as your feedback to submit the  proposal?

**Comment by iamshnoo** [comment]
@RyanMullins I have submitted a draft proposal on the portal, and also sent you the same via email along with my starter task document. Please let me know any feedback or comments if possible.

**Comment by MennatullahBasiony** [comment]
@RyanMullins  I just sent my draft proposal to you via email can you give me a feedback
