### ISSUE TITLE
[GSOC] New XAI Demos for LIT

### ISSUE THREAD

**Issue by RyanMullins** [PAIR-code/lit#665]
# Full Project

LIT is a platform for visualizing and understanding AI/ML models. We provide [demos](https://pair-code.github.io/lit/demos/) that give users a feel for how to use LIT for different tasks, and serve as examples of how to integrate LIT into user workflows. 

We are looking for someone to help us expand our demos to include new models. Possible projects include:

- **Question-answering** models
    - SQuAD, NQ, TyDi QA
- **Summarization** models
- **Tabular** models
- **Generative** models
    - Image generation models, such as a super-resolution model (image to image)
    - Image captioning models (image to text)
    - Text-to-image models
- **Masked Language** models
    - A non-english masked language model, such as XNLI or multilingual T5.
- **Classification** models
- **Multimodal** models
- **Structured Prediction** models
- **Multilingual** models
    - TyDi QA (see question-answering, above)
    - Enhance [existing XNLI demo](https://github.com/PAIR-code/lit/blob/main/lit_nlp/examples/xnli_demo.py) with new features and better documentation

Please feel free to suggest your own models or demo concepts in your applications!

# Starter Project

Given the emphasis on implementation for this project, please create an example demo that creates a LIT [Model](https://github.com/PAIR-code/lit/wiki/api.md#models) class for a publicly available [GLUE-compatible text classification model](https://huggingface.co/models?dataset=dataset:glue&language=en&pipeline_tag=text-classification&sort=downloads) (e.g., from HuggingFace’s [transformers](https://pypi.org/project/transformers/) library), then either add that model to our existing [GLUE demo](https://github.com/PAIR-code/lit/blob/main/lit_nlp/examples/glue_demo.py) or [create your own demo](https://github.com/PAIR-code/lit/wiki/api.md#adding-models-and-data) from scratch. Include a link to your example demo on GitHub (fork, PR, or Gist) or Colab in your application.

**Comment by RyanMullins** [comment]
The LIT team requires that all applications related to this topic include a link to your completed starter project for us to review (along with the standard [GSoC application requirements](https://summerofcode.withgoogle.com/how-it-works)). As such, we will not be assigning this issue to anyone because everyone interested must complete it in order to be considered.

Thanks to those who have commented, reacted, etc. for your interest. Looking forward to reviewing your applications!

**Comment by aryan1107** [comment]
Hello @RyanMullins I am very new to this and also would love to work in this project for GSoC. I just added one model to existing glue demo nothing much. I would like to know if I am doing it right for starter project. Here is my file: 

https://gist.github.com/aryan1107/554215860ada322f705c4d8a46eb656d

Screenshot from LIT
<img width="1440" alt="Screen Shot 2022-03-19 at 2 56 39 PM" src="https://user-images.githubusercontent.com/31214277/159134797-f9a540dc-5aae-40a9-973a-ddd6832a8c0a.png">

**Please let me know if I am doing correctly and is this something which the project require? I will be adding more models soon if I know if I am in right direction.**

**Comment by RyanMullins** [comment]
The application window for GSoC 2022 open today (4 Apr 2022)! Thanks to those who have reached out here, via email, etc. for you interest in this topic. I'm able to provide one round of feedback on proposals and starter projects until 15 Apr 2022. 

To received feedback:

1. Submit all content required for your starter task (demo file, model implementations, `requirements.txt`, etc.) via a GitHub PR/Gist
2. Reply to this thread and @ me (or send me an email) with a link to the PR/Gist

**Comment by Abdelrahmanrezk** [comment]
Hello @RyanMullins , is there is a time to work on that as I have start reading nlp with transformers book in chapter 2, actually, I think this can help me a lot to jump over the learning process as well as apply that here, if still there is a time to work on that I can do my best in these days, it will be great, I have also sent a starter project for tutorial on the Embedding in LIT.
