### ISSUE TITLE
Help with adding custom dataset!

### ISSUE THREAD

**Issue by aryan1107** [PAIR-code/lit#668]
Hi there I am very new to this tool, currently using this with different models for example in the picture I have used spam-classifier model. However I am having issues in terms of adding Datasets. 

Is there anyway I can use huggingface data? 
```
from datasets import load_dataset
dataset = load_dataset("sms_spam")
```

<img width="1440" alt="Screen Shot 2022-03-19 at 9 35 38 PM" src="https://user-images.githubusercontent.com/31214277/159144330-f818f580-bcbb-44f4-9b41-df5d1e35c70d.png">

**Comment by jameswex** [comment]
Details on how to create a Dataset class for use in LIT for a dataset you are interested can be found at https://github.com/PAIR-code/lit/wiki/api.md#datasets

You should be able to run load_dataset inside of a LIT Dataset class.

**Comment by aryan1107** [comment]
Thank you so much I was able to add it. I will be closing this thread.
