### ISSUE TITLE
Need help with text generation models!

### ISSUE THREAD

**Issue by aryan1107** [PAIR-code/lit#670]
I am very new to this tool. I am now successfully able to use classification models. However now I am getting stuck at text generation models. For example in the picture below there is Question and Context and based on that it generates text.

So in this case I haven't added label in my model class as it doesn't classify based on label. How do I show text generated field?

<img width="1438" alt="Screen Shot 2022-03-21 at 6 37 50 PM" src="https://user-images.githubusercontent.com/31214277/159375728-4fb97a83-b15a-40a9-8cfa-02a2a384bf08.png">

**Comment by jameswex** [comment]
As per https://github.com/PAIR-code/lit/wiki/components.md#seq2seq--generation, you can have a field in your model's output spec of type GeneratedText and return the generated string as the value of that field in your predict_minibatch function.

**Comment by aryan1107** [comment]
Thanks for your response I will try.
