### ISSUE TITLE
Demo example to display attention

### ISSUE THREAD

**Issue by zero-you** [PAIR-code/lit#7]
Hi,
The example folder does not seem to have the code that generates the screen shot in readme:
https://github.com/PAIR-code/lit/blob/main/docs/images/figure-1.png

I was not able to figure out how to get attention displayed in UI by looking at the two examples (quickstart_sst_demo, quickstart_sst_demo) provided in the readme. Would really appreciate if you could add the example mentioned above.

Thanks!

**Comment by iftenney** [comment]
Whoops! For illustration purposes, the screenshot in the README has a slightly different layout than the actual demo (see [layout.ts](https://github.com/PAIR-code/lit/blob/main/lit_nlp/client/layout.ts)). In the `default` layout, Attention should be under the "Explanations" tab, on the right side.

**Comment by zero-you** [comment]
> Whoops! For illustration purposes, the screenshot in the README has a slightly different layout than the actual demo (see [layout.ts](https://github.com/PAIR-code/lit/blob/main/lit_nlp/client/layout.ts)). In the `default` layout, Attention should be under the "Explanations" tab, on the right side.

Switching to "default" layout works! Thanks!
