### ISSUE TITLE
GSoC - Demos Project: Multi-Lingual Demo for the TyDi QA Task

### ISSUE THREAD

**Issue by RyanMullins** [PAIR-code/lit#746]
Goal: Add a demo with a multilingual model on the TyDi AQ task

Branch off of `dev`. 

* [x] Dataset
    * [x] Make a Dataset wrapper for the TyDi QA dataset in the `./lit_nlp/examples/datasets` directory
* [x] Model
    * [x] Find a compatible model in Hugging Face
    * [x] Make a Model wrapper class in the `./lit_nlp/examples/models` directory
    * [x] Add unit tests (see examples in `./lit_nlp/examples/models/*_test.py` files)
* [x] Demo
    * [x] Make a demo file called `tydi_demo.py` in the `./lit_nlp/examples` directory
    * [x] Import the TyDi QA dataset
    * [x] Import the model
    * [x] Configure the demo layout

**Comment by aryan1107** [comment]
Some compatible models (will add more):

- [Narrativa/mT5-base-finetuned-tydiQA-xqa](https://huggingface.co/Narrativa/mT5-base-finetuned-tydiQA-xqa)
