### ISSUE TITLE
Will this work for an OpenNMT model?

### ISSUE THREAD

**Issue by brighi018** [PAIR-code/lit#94]
Hi, I've been trying to use LIT with a pre-trained OpenNMT model and am having a lot of trouble with creating the Model class. I'm not sure what the closest example you have is, but I haven't had any luck with what I've tried. Do you have an example demo/class for OpenNMT models?

**Comment by iftenney** [comment]
We don't have an example specifically for OpenNMT, but there's a seq2seq demo using T5 here: https://github.com/PAIR-code/lit/blob/main/lit_nlp/examples/t5_summarization_demo.py using this model class https://github.com/PAIR-code/lit/blob/main/lit_nlp/examples/models/t5.py

For a simple NMT demo, you could use a spec like:
```
def input_spec():
    return {'source': TextSegment()}

def output_spec():
    return {'translation': GeneratedText()}
```
