### ISSUE TITLE
Web-based demo (eventually)?

### ISSUE THREAD

**Issue by drscotthawley** [PAIR-code/lit#97]
I've loved the way the hosted web demos by PAIR make it easy for people (e.g. my students, a couple of whom got to meet Mahima!) to just try them out immediately -- such as the What-If Tool and the Embedding Projector.  Currently it seems that LIT is only possible to run by installing it locally. I understand it is still in the "work in progress" stage but wanted to ask: Are there plans to make it available as a web-based demo as well?  Thanks.

**Comment by iftenney** [comment]
Yup! This is definitely on the roadmap, and coming very soon (we hope) :)

**Comment by jameswex** [comment]
Hi Scott! We're really hopeful that LIT can be at least as educationally-valuable as WIT. As Ian says, web demos are for sure coming.

**Comment by iftenney** [comment]
Web-based demos now available! Check out https://pair-code.github.io/lit/demos/
