### ISSUE TITLE
Almost working Google Colab example

### ISSUE THREAD

**Issue by g-simmons** [PAIR-code/lit#987]
Hey there,

The example notebook has a comment saying that LIT does not work on Colab since the Colab python version is fixed to 3.7.

I have been trying to get LIT to work on Colab by upgrading the Python version, and I think I have some progress? I can import the lit_nlp library and create the widget, the only issue is widget.render() produces a blank output.

I'm hoping the LIT devs can provide troubleshooting input on how I might get this to work.
[
Current notebook version](https://colab.research.google.com/gist/g-simmons/108807ce06c853cbbf558f1f7215a6b4/lit_colab_second_attempt.ipynb).

**Comment by uSaiPrashanth** [comment]
What helped me fix this problem is to manually assign is_colab to true after importing notebook in colab

Here's a short example of what I ended up doing...

```py
from lit_nlp import notebook
notebook.is_colab = True

# Rest of code cells

widget = notebook.LitWidget({'model': lit_model}, {'ds': lit_dataset})
# lit_model is a lit_nlp.api.model.Model instance
# lit_dataset is a lit_nlp.api.dataset.Dataset instance

widget.render(height = 600)
```

**Comment by RyanMullins** [comment]
Colab is running Python v3.10 as of Apr 2023 (see https://github.com/googlecolab/colabtools/issues/3572) so the Notebooks should work out of the box again. I've recently submitted a PR to remove this warning text (https://github.com/PAIR-code/lit/commit/806e41dbbbadd2211cc25b3583f41ed896a195d0), but this may not update on  Colab until our next release.

Closing this issue for now, but please re-open or file a new one if you run into any issues.
